### PR TITLE
Support multi-key indexes

### PR DESCRIPTION
**Pull request by ajoslin**

### CODE REVIEW

**Comment by sethvincent** [comment]
Cool, thank you so much! I've been meaning to add this.

**Comment by ajoslin** [comment]
Definitely. Thanks for the lib!

**Comment by ajoslin** [comment]
Can you publish a release for this?

**Comment by sethvincent** [comment]
🎉 📦 v2.1.0

I can add you on npm to this and level-model, too if you're interested.

**Comment by ajoslin** [comment]
I re-opened #4 because this implementation is just wrong!

Now that I know the library (after going through the intense recursion in #4), I'd be down with having NPM access. I'll follow semver and ask if I think the release is a big deal.

**Pull request merged**
